__title__ = 'tk_gui'
__description__ = 'TK GUI'
__url__ = 'https://github.com/dskrypa/tk_gui'
__version__ = '2024.12.14-3'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2024 Doug Skrypa'
